name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    # - uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     auto-update-conda: true
    #     python-version:  3.7.1
    # Definitely not the best practice
    # - name: Create coq_gym conda env
    #   run: |
    #     conda env create -f CoqGym/CoqGym/coq_gym.yml && conda activate coq_gym
    # # - name: What is happening
    # #   run: |
    # #     ls -R
    
    - name: Install conda env
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    
    - name: create CoqGym package
      run: |
        pip install -e CoqGym

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8 `find . -name "*.py" -not -path "./CoqGym/*"`
